services:
  postgres:
    image: postgres:15
    # container_name: ytaudio-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ytaudio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ytaudio"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    # container_name: ytaudio-redis

  api:
    build: 
      context: ../../
      dockerfile: apps/api/Dockerfile
    # container_name: ytaudio-api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../../.env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    volumes:
      - ../../downloads:/app/downloads
    restart: always

  worker:
    build: 
      context: ../../
      dockerfile: apps/worker/Dockerfile
    # container_name: ytaudio-worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../../.env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    volumes:
      - ../../downloads:/app/downloads
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
